import type { PrismaClient } from "../src/generated/prisma/client"
import { HIDDEN_FACE_SLUG, MAGICAL_RACE_SLUG, NEM_A_PATO_SLUG } from "@/modules/games"
const verifiedAt = new Date("2026-07-30T00:00:00.000Z")

const categories = [
	{ slug: "mundo", name: "Mundo" },
	{ slug: "ciencia", name: "Ciência" },
	{ slug: "historia", name: "História" },
	{ slug: "tecnologia", name: "Tecnologia" },
	{ slug: "entretenimento", name: "Entretenimento" },
	{ slug: "esportes", name: "Esportes" },
	{ slug: "natureza", name: "Natureza" },
	{ slug: "cotidiano", name: "Cotidiano" },
] as const

const difficulties = [
	{ slug: "facil", name: "Fácil", legacyValue: "EASY" },
	{ slug: "media", name: "Média", legacyValue: "MEDIUM" },
	{ slug: "dificil", name: "Difícil", legacyValue: "HARD" },
] as const

type SeedQuestion = {
	categorySlug: (typeof categories)[number]["slug"]
	prompt: string
	answerValue: string
	answerText: string
	answerUnit: string
	explanation: string
	sourceName: string
	sourceUrl: string
	difficulty: (typeof difficulties)[number]["legacyValue"]
}

const questions: SeedQuestion[] = [
	{
		categorySlug: "mundo",
		prompt: "Quantos Estados-membros a ONU possui?",
		answerValue: "193",
		answerText: "193 Estados-membros",
		answerUnit: "Estados-membros",
		explanation: "A Organização das Nações Unidas reúne 193 Estados-membros.",
		sourceName: "Nações Unidas",
		sourceUrl: "https://www.un.org/en/about-us/member-states",
		difficulty: "EASY",
	},
	{
		categorySlug: "mundo",
		prompt: "Quantos países fazem fronteira terrestre com o Brasil?",
		answerValue: "10",
		answerText: "10 países",
		answerUnit: "países",
		explanation:
			"O Brasil faz fronteira com todos os países sul-americanos, exceto Chile e Equador.",
		sourceName: "IBGE",
		sourceUrl:
			"https://atlasescolar.ibge.gov.br/brasil/2996-divisao-politica-e-regional/20397-fronteiras-do-brasil.html",
		difficulty: "MEDIUM",
	},
	{
		categorySlug: "mundo",
		prompt: "Qual é a área total da Rússia, em quilômetros quadrados?",
		answerValue: "17098242",
		answerText: "17.098.242 km²",
		answerUnit: "km²",
		explanation: "A Rússia é o maior país do mundo em área total.",
		sourceName: "Banco Mundial",
		sourceUrl: "https://data.worldbank.org/indicator/AG.LND.TOTL.K2?locations=RU",
		difficulty: "HARD",
	},
	{
		categorySlug: "mundo",
		prompt: "Quantos municípios o Brasil tem?",
		answerValue: "5570",
		answerText: "5.570 municípios",
		answerUnit: "municípios",
		explanation: "A divisão territorial brasileira possui 5.570 municípios.",
		sourceName: "IBGE",
		sourceUrl: "https://www.ibge.gov.br/cidades-e-estados.html",
		difficulty: "MEDIUM",
	},
	{
		categorySlug: "ciencia",
		prompt: "Qual é a distância média entre a Terra e a Lua, em quilômetros?",
		answerValue: "384400",
		answerText: "cerca de 384.400 km",
		answerUnit: "km",
		explanation: "A distância varia ao longo da órbita lunar; este é seu valor médio.",
		sourceName: "NASA",
		sourceUrl: "https://science.nasa.gov/moon/facts/",
		difficulty: "MEDIUM",
	},
	{
		categorySlug: "ciencia",
		prompt: "Quantos planetas há no Sistema Solar?",
		answerValue: "8",
		answerText: "8 planetas",
		answerUnit: "planetas",
		explanation:
			"Mercúrio, Vênus, Terra, Marte, Júpiter, Saturno, Urano e Netuno são os planetas reconhecidos.",
		sourceName: "NASA",
		sourceUrl: "https://science.nasa.gov/solar-system/planets/",
		difficulty: "EASY",
	},
	{
		categorySlug: "ciencia",
		prompt: "A que temperatura a água pura ferve ao nível do mar, em graus Celsius?",
		answerValue: "100",
		answerText: "100 °C",
		answerUnit: "°C",
		explanation: "A temperatura de ebulição depende da pressão; ao nível do mar, é 100 °C.",
		sourceName: "NIST",
		sourceUrl: "https://www.nist.gov/pml/owm/metric-si/si-units",
		difficulty: "EASY",
	},
	{
		categorySlug: "ciencia",
		prompt: "Qual é a velocidade da luz no vácuo, em metros por segundo?",
		answerValue: "299792458",
		answerText: "299.792.458 m/s",
		answerUnit: "m/s",
		explanation: "O metro é definido a partir deste valor exato da velocidade da luz no vácuo.",
		sourceName: "BIPM",
		sourceUrl: "https://www.bipm.org/en/si-base-units",
		difficulty: "HARD",
	},
	{
		categorySlug: "historia",
		prompt: "Em que ano foi declarada a Independência do Brasil?",
		answerValue: "1822",
		answerText: "1822",
		answerUnit: "ano",
		explanation: "A Independência foi proclamada em 7 de setembro de 1822.",
		sourceName: "Arquivo Nacional",
		sourceUrl:
			"https://www.gov.br/arquivonacional/pt-br/assuntos/educacao/recursos-educacionais/independencia-do-brasil",
		difficulty: "EASY",
	},
	{
		categorySlug: "historia",
		prompt: "Em que ano caiu o Muro de Berlim?",
		answerValue: "1989",
		answerText: "1989",
		answerUnit: "ano",
		explanation: "A abertura do muro ocorreu em 9 de novembro de 1989.",
		sourceName: "Museu do Muro de Berlim",
		sourceUrl: "https://www.berliner-mauer-gedenkstaette.de/en/history-of-the-berlin-wall-916.html",
		difficulty: "MEDIUM",
	},
	{
		categorySlug: "historia",
		prompt: "Quantos anos durou a Primeira Guerra Mundial, de 1914 a 1918?",
		answerValue: "4",
		answerText: "4 anos",
		answerUnit: "anos",
		explanation: "O conflito começou em julho de 1914 e terminou em novembro de 1918.",
		sourceName: "Imperial War Museums",
		sourceUrl: "https://www.iwm.org.uk/history/first-world-war",
		difficulty: "EASY",
	},
	{
		categorySlug: "historia",
		prompt: "Em que ano a Organização das Nações Unidas foi fundada?",
		answerValue: "1945",
		answerText: "1945",
		answerUnit: "ano",
		explanation: "A Carta das Nações Unidas entrou em vigor em 24 de outubro de 1945.",
		sourceName: "Nações Unidas",
		sourceUrl: "https://www.un.org/en/about-us/history-of-the-un",
		difficulty: "MEDIUM",
	},
	{
		categorySlug: "tecnologia",
		prompt: "Qual é a porta padrão do protocolo HTTP?",
		answerValue: "80",
		answerText: "porta 80",
		answerUnit: "porta",
		explanation: "HTTP é registrado pela IANA na porta 80.",
		sourceName: "IANA",
		sourceUrl:
			"https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=http",
		difficulty: "EASY",
	},
	{
		categorySlug: "tecnologia",
		prompt: "Qual é a porta padrão do protocolo HTTPS?",
		answerValue: "443",
		answerText: "porta 443",
		answerUnit: "porta",
		explanation: "HTTPS é registrado pela IANA na porta 443.",
		sourceName: "IANA",
		sourceUrl:
			"https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=https",
		difficulty: "EASY",
	},
	{
		categorySlug: "tecnologia",
		prompt: "Quantos bits formam um byte?",
		answerValue: "8",
		answerText: "8 bits",
		answerUnit: "bits",
		explanation: "Um byte é composto por oito bits.",
		sourceName: "NIST",
		sourceUrl: "https://physics.nist.gov/cuu/Units/binary.html",
		difficulty: "EASY",
	},
	{
		categorySlug: "tecnologia",
		prompt: "Em que ano o primeiro iPhone foi lançado?",
		answerValue: "2007",
		answerText: "2007",
		answerUnit: "ano",
		explanation: "O iPhone original foi lançado nos Estados Unidos em 2007.",
		sourceName: "Apple",
		sourceUrl: "https://www.apple.com/newsroom/2007/06/29Apple-Sells-One-Millionth-iPhone/",
		difficulty: "MEDIUM",
	},
	{
		categorySlug: "entretenimento",
		prompt: "Quantas estatuetas foram entregues na primeira cerimônia do Oscar?",
		answerValue: "15",
		answerText: "15 estatuetas",
		answerUnit: "estatuetas",
		explanation: "A primeira cerimônia, em 1929, premiou 15 vencedores.",
		sourceName: "Academy of Motion Picture Arts and Sciences",
		sourceUrl: "https://www.oscars.org/oscars/ceremonies/1929",
		difficulty: "HARD",
	},
	{
		categorySlug: "entretenimento",
		prompt: "Quantos episódios tem a primeira temporada de Chaves?",
		answerValue: "33",
		answerText: "33 episódios",
		answerUnit: "episódios",
		explanation: "A primeira temporada da série foi exibida em 1972.",
		sourceName: "IMDb",
		sourceUrl: "https://www.imdb.com/title/tt0229889/episodes/?season=1",
		difficulty: "HARD",
	},
	{
		categorySlug: "entretenimento",
		prompt: "Em que ano foi lançado o primeiro filme da franquia Toy Story?",
		answerValue: "1995",
		answerText: "1995",
		answerUnit: "ano",
		explanation: "Toy Story estreou nos cinemas em 1995.",
		sourceName: "Pixar",
		sourceUrl: "https://www.pixar.com/toy-story",
		difficulty: "MEDIUM",
	},
	{
		categorySlug: "entretenimento",
		prompt: "Quantos livros compõem a série principal Harry Potter?",
		answerValue: "7",
		answerText: "7 livros",
		answerUnit: "livros",
		explanation: "A história principal acompanha Harry Potter em sete romances.",
		sourceName: "Wizarding World",
		sourceUrl: "https://www.wizardingworld.com/collections/harry-potter-books",
		difficulty: "EASY",
	},
	{
		categorySlug: "esportes",
		prompt: "Quantos jogadores cada time mantém em campo em uma partida de futebol?",
		answerValue: "11",
		answerText: "11 jogadores",
		answerUnit: "jogadores",
		explanation: "As Leis do Jogo definem o máximo de onze jogadores por equipe em campo.",
		sourceName: "FIFA",
		sourceUrl:
			"https://digitalhub.fifa.com/m/24f3d1dce0ff4823/original/Football-Additional-Laws-of-the-Game-2025-26.pdf",
		difficulty: "EASY",
	},
	{
		categorySlug: "esportes",
		prompt:
			"Quantos sets um tenista precisa vencer, no máximo, em uma partida masculina de Grand Slam?",
		answerValue: "3",
		answerText: "3 sets",
		answerUnit: "sets",
		explanation: "Partidas masculinas de Grand Slam são disputadas em melhor de cinco sets.",
		sourceName: "ITF",
		sourceUrl: "https://www.itftennis.com/en/about-us/governance/rules-and-regulations/",
		difficulty: "MEDIUM",
	},
	{
		categorySlug: "esportes",
		prompt: "Qual é a distância oficial de uma maratona, em metros?",
		answerValue: "42195",
		answerText: "42.195 metros",
		answerUnit: "metros",
		explanation: "A distância oficial da maratona é de 42,195 quilômetros.",
		sourceName: "World Athletics",
		sourceUrl: "https://worldathletics.org/disciplines/road-running/marathon",
		difficulty: "MEDIUM",
	},
	{
		categorySlug: "esportes",
		prompt: "Quantos pontos vale um touchdown no futebol americano?",
		answerValue: "6",
		answerText: "6 pontos",
		answerUnit: "pontos",
		explanation: "Um touchdown vale seis pontos antes de qualquer tentativa extra.",
		sourceName: "NFL",
		sourceUrl: "https://operations.nfl.com/the-rules/nfl-rulebook/",
		difficulty: "EASY",
	},
	{
		categorySlug: "natureza",
		prompt: "Quantos braços possui tipicamente um polvo?",
		answerValue: "8",
		answerText: "8 braços",
		answerUnit: "braços",
		explanation: "Polvos têm oito braços, cada um com ventosas.",
		sourceName: "Smithsonian Ocean",
		sourceUrl: "https://ocean.si.edu/ocean-life/invertebrates/octopuses-and-squids",
		difficulty: "EASY",
	},
	{
		categorySlug: "natureza",
		prompt: "Quantas espécies de grandes felinos existem no gênero Panthera?",
		answerValue: "5",
		answerText: "5 espécies",
		answerUnit: "espécies",
		explanation:
			"Leão, tigre, leopardo, onça-pintada e leopardo-das-neves pertencem ao gênero Panthera.",
		sourceName: "San Diego Zoo Wildlife Alliance",
		sourceUrl: "https://animals.sandiegozoo.org/animals/jaguar",
		difficulty: "HARD",
	},
	{
		categorySlug: "natureza",
		prompt: "Quantas câmaras tem o coração de um mamífero?",
		answerValue: "4",
		answerText: "4 câmaras",
		answerUnit: "câmaras",
		explanation: "O coração de mamíferos possui dois átrios e dois ventrículos.",
		sourceName: "National Heart, Lung, and Blood Institute",
		sourceUrl: "https://www.nhlbi.nih.gov/health/heart/anatomy",
		difficulty: "EASY",
	},
	{
		categorySlug: "cotidiano",
		prompt: "Quantos litros há em um metro cúbico?",
		answerValue: "1000",
		answerText: "1.000 litros",
		answerUnit: "litros",
		explanation: "Um metro cúbico equivale a mil litros.",
		sourceName: "BIPM",
		sourceUrl: "https://www.bipm.org/en/si-base-units",
		difficulty: "EASY",
	},
	{
		categorySlug: "cotidiano",
		prompt: "Quantos minutos há em uma semana?",
		answerValue: "10080",
		answerText: "10.080 minutos",
		answerUnit: "minutos",
		explanation: "Sete dias multiplicados por 24 horas e 60 minutos totalizam 10.080 minutos.",
		sourceName: "NIST",
		sourceUrl:
			"https://www.nist.gov/pml/time-and-frequency-division/popular-links/time-frequency-z",
		difficulty: "MEDIUM",
	},
	{
		categorySlug: "cotidiano",
		prompt: "Quantos mililitros há em uma colher de sopa dos Estados Unidos?",
		answerValue: "14.7868",
		answerText: "14,7868 mL",
		answerUnit: "mL",
		explanation:
			"A colher de sopa dos Estados Unidos equivale a aproximadamente 14,7868 mililitros.",
		sourceName: "NIST",
		sourceUrl: "https://www.nist.gov/pml/owm/metric-si/si-units",
		difficulty: "HARD",
	},
	{
		categorySlug: "mundo",
		prompt: "Quantos oceanos são geralmente reconhecidos na Terra?",
		answerValue: "5",
		answerText: "5 oceanos",
		answerUnit: "oceanos",
		explanation: "São reconhecidos os oceanos Pacífico, Atlântico, Índico, Ártico e Antártico.",
		sourceName: "NOAA Ocean Service",
		sourceUrl: "https://oceanservice.noaa.gov/facts/howmanyoceans.html",
		difficulty: "EASY",
	},
	{
		categorySlug: "mundo",
		prompt: "Quantos países formam o Reino Unido?",
		answerValue: "4",
		answerText: "4 países",
		answerUnit: "países",
		explanation: "Inglaterra, Escócia, País de Gales e Irlanda do Norte formam o Reino Unido.",
		sourceName: "GOV.UK",
		sourceUrl:
			"https://www.gov.uk/government/publications/uk-facts-and-figures/uk-facts-and-figures",
		difficulty: "EASY",
	},
	{
		categorySlug: "ciencia",
		prompt: "Quantos ossos há normalmente no corpo de um ser humano adulto?",
		answerValue: "206",
		answerText: "206 ossos",
		answerUnit: "ossos",
		explanation: "O esqueleto humano adulto é normalmente composto por 206 ossos.",
		sourceName: "Cleveland Clinic",
		sourceUrl: "https://my.clevelandclinic.org/health/body/21048-skeletal-system",
		difficulty: "MEDIUM",
	},
	{
		categorySlug: "ciencia",
		prompt: "Quantos elementos químicos estão reconhecidos na tabela periódica?",
		answerValue: "118",
		answerText: "118 elementos",
		answerUnit: "elementos",
		explanation: "A tabela periódica da IUPAC reconhece 118 elementos químicos nomeados.",
		sourceName: "IUPAC",
		sourceUrl: "https://iupac.org/what-we-do/periodic-table-of-elements/",
		difficulty: "MEDIUM",
	},
	{
		categorySlug: "historia",
		prompt: "Em que ano os primeiros seres humanos pousaram na Lua?",
		answerValue: "1969",
		answerText: "1969",
		answerUnit: "ano",
		explanation: "A missão Apollo 11 pousou na Lua em 20 de julho de 1969.",
		sourceName: "NASA",
		sourceUrl: "https://www.nasa.gov/mission/apollo-11/",
		difficulty: "EASY",
	},
	{
		categorySlug: "historia",
		prompt: "Em que ano foi proclamada a República no Brasil?",
		answerValue: "1889",
		answerText: "1889",
		answerUnit: "ano",
		explanation: "A República foi proclamada em 15 de novembro de 1889.",
		sourceName: "Senado Federal",
		sourceUrl: "https://www12.senado.leg.br/noticias/entenda-o-assunto/proclamacao-da-republica",
		difficulty: "MEDIUM",
	},
	{
		categorySlug: "tecnologia",
		prompt: "Quantos bytes formam um kibibyte?",
		answerValue: "1024",
		answerText: "1.024 bytes",
		answerUnit: "bytes",
		explanation: "O prefixo binário kibi representa 2 elevado à décima potência, ou 1.024.",
		sourceName: "NIST",
		sourceUrl: "https://physics.nist.gov/cuu/Units/binary.html",
		difficulty: "MEDIUM",
	},
	{
		categorySlug: "tecnologia",
		prompt: "Em que ano a primeira página da World Wide Web foi publicada?",
		answerValue: "1991",
		answerText: "1991",
		answerUnit: "ano",
		explanation: "Tim Berners-Lee publicou a primeira página da web em 6 de agosto de 1991.",
		sourceName: "CERN",
		sourceUrl: "https://home.cern/science/computing/birth-web",
		difficulty: "HARD",
	},
	{
		categorySlug: "entretenimento",
		prompt: "Quantos integrantes formavam o grupo ABBA?",
		answerValue: "4",
		answerText: "4 integrantes",
		answerUnit: "integrantes",
		explanation: "O grupo sueco era formado por Agnetha, Björn, Benny e Anni-Frid.",
		sourceName: "ABBA",
		sourceUrl: "https://abbasite.com/about/",
		difficulty: "EASY",
	},
	{
		categorySlug: "entretenimento",
		prompt: "Quantos filmes compõem a trilogia O Senhor dos Anéis dirigida por Peter Jackson?",
		answerValue: "3",
		answerText: "3 filmes",
		answerUnit: "filmes",
		explanation: "A trilogia é formada por A Sociedade do Anel, As Duas Torres e O Retorno do Rei.",
		sourceName: "The Lord of the Rings",
		sourceUrl: "https://www.lotr.com/",
		difficulty: "EASY",
	},
	{
		categorySlug: "esportes",
		prompt: "Quantos anéis há no símbolo olímpico?",
		answerValue: "5",
		answerText: "5 anéis",
		answerUnit: "anéis",
		explanation: "Os cinco anéis entrelaçados são um dos símbolos mais reconhecidos do olimpismo.",
		sourceName: "Comitê Olímpico Internacional",
		sourceUrl: "https://olympics.com/ioc/olympic-symbol",
		difficulty: "EASY",
	},
	{
		categorySlug: "esportes",
		prompt: "Quantos pontos vale um lance livre convertido no basquete?",
		answerValue: "1",
		answerText: "1 ponto",
		answerUnit: "ponto",
		explanation: "Cada lance livre convertido vale um ponto no placar.",
		sourceName: "FIBA",
		sourceUrl: "https://www.fiba.basketball/documents/official-basketball-rules/current.pdf",
		difficulty: "EASY",
	},
	{
		categorySlug: "natureza",
		prompt: "Quantas patas tem uma aranha?",
		answerValue: "8",
		answerText: "8 patas",
		answerUnit: "patas",
		explanation: "Aranhas são aracnídeos e têm quatro pares de patas.",
		sourceName: "Smithsonian National Museum of Natural History",
		sourceUrl: "https://naturalhistory.si.edu/education/teaching-resources/life-science/spiders",
		difficulty: "EASY",
	},
	{
		categorySlug: "natureza",
		prompt: "Quantas vértebras cervicais tem uma girafa?",
		answerValue: "7",
		answerText: "7 vértebras cervicais",
		answerUnit: "vértebras",
		explanation: "Assim como a maioria dos mamíferos, a girafa tem sete vértebras no pescoço.",
		sourceName: "San Diego Zoo Wildlife Alliance",
		sourceUrl: "https://animals.sandiegozoo.org/animals/giraffe",
		difficulty: "MEDIUM",
	},
	{
		categorySlug: "cotidiano",
		prompt: "Quantos segundos há em 24 horas?",
		answerValue: "86400",
		answerText: "86.400 segundos",
		answerUnit: "segundos",
		explanation: "Um dia de 24 horas tem 86.400 segundos.",
		sourceName: "NIST",
		sourceUrl:
			"https://www.nist.gov/pml/time-and-frequency-division/popular-links/time-frequency-z",
		difficulty: "MEDIUM",
	},
	{
		categorySlug: "cotidiano",
		prompt: "Quantas faces tem um dodecaedro regular?",
		answerValue: "12",
		answerText: "12 faces",
		answerUnit: "faces",
		explanation: "Um dodecaedro regular é um sólido geométrico formado por doze faces pentagonais.",
		sourceName: "Encyclopaedia Britannica",
		sourceUrl: "https://www.britannica.com/science/dodecahedron",
		difficulty: "MEDIUM",
	},
	{
		categorySlug: "mundo",
		prompt: "Qual é a área total do Brasil, em quilômetros quadrados?",
		answerValue: "8515767",
		answerText: "8.515.767 km²",
		answerUnit: "km²",
		explanation: "O território brasileiro ocupa mais de 8,5 milhões de quilômetros quadrados.",
		sourceName: "IBGE",
		sourceUrl:
			"https://www.ibge.gov.br/geociencias/organizacao-do-territorio/estrutura-territorial/15761-areas-dos-municipios.html",
		difficulty: "HARD",
	},
	{
		categorySlug: "mundo",
		prompt: "Qual é a área total do Canadá, em quilômetros quadrados?",
		answerValue: "9984670",
		answerText: "9.984.670 km²",
		answerUnit: "km²",
		explanation: "O Canadá é o segundo maior país do mundo em área total.",
		sourceName: "Encyclopaedia Britannica",
		sourceUrl: "https://www.britannica.com/place/Canada",
		difficulty: "HARD",
	},
	{
		categorySlug: "mundo",
		prompt: "Qual é a área total da China, em quilômetros quadrados?",
		answerValue: "9596961",
		answerText: "9.596.961 km²",
		answerUnit: "km²",
		explanation: "A China ocupa cerca de 9,6 milhões de quilômetros quadrados.",
		sourceName: "Encyclopaedia Britannica",
		sourceUrl: "https://www.britannica.com/place/China",
		difficulty: "HARD",
	},
	{
		categorySlug: "mundo",
		prompt: "Qual é a área aproximada do Oceano Pacífico, em quilômetros quadrados?",
		answerValue: "165250000",
		answerText: "cerca de 165.250.000 km²",
		answerUnit: "km²",
		explanation: "O Pacífico é o maior e mais profundo oceano da Terra.",
		sourceName: "NOAA Ocean Service",
		sourceUrl: "https://oceanservice.noaa.gov/facts/biggestocean.html",
		difficulty: "HARD",
	},
	{
		categorySlug: "mundo",
		prompt: "Qual é a extensão aproximada do rio Nilo, em quilômetros?",
		answerValue: "6650",
		answerText: "cerca de 6.650 km",
		answerUnit: "km",
		explanation: "O Nilo percorre o nordeste da África até desaguar no Mediterrâneo.",
		sourceName: "Encyclopaedia Britannica",
		sourceUrl: "https://www.britannica.com/place/Nile-River",
		difficulty: "MEDIUM",
	},
	{
		categorySlug: "ciencia",
		prompt: "Qual é a distância média entre a Terra e o Sol, em quilômetros?",
		answerValue: "149600000",
		answerText: "cerca de 149.600.000 km",
		answerUnit: "km",
		explanation: "Essa distância média é conhecida como uma unidade astronômica.",
		sourceName: "NASA",
		sourceUrl: "https://science.nasa.gov/exoplanets/what-is-the-habitable-zone-or-goldilocks-zone/",
		difficulty: "HARD",
	},
	{
		categorySlug: "ciencia",
		prompt: "Qual é o diâmetro aproximado do Sol, em quilômetros?",
		answerValue: "1392700",
		answerText: "cerca de 1.392.700 km",
		answerUnit: "km",
		explanation: "O Sol concentra praticamente toda a massa do Sistema Solar.",
		sourceName: "NASA",
		sourceUrl: "https://science.nasa.gov/sun/facts/",
		difficulty: "HARD",
	},
	{
		categorySlug: "ciencia",
		prompt: "Qual é o diâmetro aproximado de Júpiter, em quilômetros?",
		answerValue: "142984",
		answerText: "cerca de 142.984 km",
		answerUnit: "km",
		explanation: "Júpiter é o maior planeta do Sistema Solar.",
		sourceName: "NASA",
		sourceUrl: "https://science.nasa.gov/jupiter/facts/",
		difficulty: "HARD",
	},
	{
		categorySlug: "ciencia",
		prompt: "Qual é a circunferência aproximada da Terra no Equador, em quilômetros?",
		answerValue: "40075",
		answerText: "cerca de 40.075 km",
		answerUnit: "km",
		explanation: "A Terra é levemente achatada nos polos, por isso a medida equatorial é maior.",
		sourceName: "NASA",
		sourceUrl: "https://science.nasa.gov/earth/facts/",
		difficulty: "MEDIUM",
	},
	{
		categorySlug: "ciencia",
		prompt: "Qual é a idade aproximada da Terra, em anos?",
		answerValue: "4540000000",
		answerText: "cerca de 4.540.000.000 anos",
		answerUnit: "anos",
		explanation: "A idade é estimada com base em rochas terrestres, lunares e meteoritos.",
		sourceName: "U.S. Geological Survey",
		sourceUrl: "https://pubs.usgs.gov/gip/geotime/age.html",
		difficulty: "HARD",
	},
	{
		categorySlug: "ciencia",
		prompt: "Quantos mililitros há em um quilômetro cúbico?",
		answerValue: "1000000000000000",
		answerText: "1.000.000.000.000.000 mL",
		answerUnit: "mL",
		explanation:
			"Um quilômetro cúbico equivale a um trilhão de litros, ou um quatrilhão de mililitros.",
		sourceName: "BIPM",
		sourceUrl: "https://www.bipm.org/en/measurement-units/si-prefixes",
		difficulty: "HARD",
	},
	{
		categorySlug: "tecnologia",
		prompt: "Quantos endereços distintos existem no espaço de endereçamento IPv4?",
		answerValue: "4294967296",
		answerText: "4.294.967.296 endereços",
		answerUnit: "endereços",
		explanation: "Um endereço IPv4 possui 32 bits, permitindo 2 elevado a 32 combinações.",
		sourceName: "IETF",
		sourceUrl: "https://www.rfc-editor.org/rfc/rfc791",
		difficulty: "HARD",
	},
	{
		categorySlug: "tecnologia",
		prompt: "Quantos bytes há em um tebibyte?",
		answerValue: "1099511627776",
		answerText: "1.099.511.627.776 bytes",
		answerUnit: "bytes",
		explanation: "O prefixo binário tebi representa 2 elevado à quadragésima potência.",
		sourceName: "NIST",
		sourceUrl: "https://physics.nist.gov/cuu/Units/binary.html",
		difficulty: "HARD",
	},
	{
		categorySlug: "tecnologia",
		prompt: "Qual é o maior valor possível em um inteiro sem sinal de 32 bits?",
		answerValue: "4294967295",
		answerText: "4.294.967.295",
		answerUnit: "valor",
		explanation: "Com 32 bits, os valores sem sinal vão de zero até 2 elevado a 32 menos um.",
		sourceName: "NIST",
		sourceUrl: "https://physics.nist.gov/cuu/Units/binary.html",
		difficulty: "HARD",
	},
	{
		categorySlug: "tecnologia",
		prompt: "Qual é o maior número de porta disponível em TCP e UDP?",
		answerValue: "65535",
		answerText: "65.535",
		answerUnit: "porta",
		explanation: "Os números de porta usam 16 bits, indo de zero a 65.535.",
		sourceName: "IANA",
		sourceUrl:
			"https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml",
		difficulty: "MEDIUM",
	},
	{
		categorySlug: "tecnologia",
		prompt: "Qual é o maior valor de segundos de um contador Unix assinado de 32 bits?",
		answerValue: "2147483647",
		answerText: "2.147.483.647 segundos",
		answerUnit: "segundos",
		explanation:
			"Esse limite corresponde ao conhecido problema do ano 2038 em sistemas de 32 bits.",
		sourceName: "The Open Group",
		sourceUrl: "https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/time.h.html",
		difficulty: "HARD",
	},
	{
		categorySlug: "historia",
		prompt: "Em que ano os portugueses chegaram ao território que viria a ser o Brasil?",
		answerValue: "1500",
		answerText: "1500",
		answerUnit: "ano",
		explanation: "A frota de Pedro Álvares Cabral chegou à costa em abril de 1500.",
		sourceName: "Arquivo Nacional",
		sourceUrl:
			"https://www.gov.br/arquivonacional/pt-br/assuntos/educacao/recursos-educacionais/descobrimento-do-brasil",
		difficulty: "EASY",
	},
	{
		categorySlug: "historia",
		prompt: "Em que ano começou a Revolução Francesa?",
		answerValue: "1789",
		answerText: "1789",
		answerUnit: "ano",
		explanation: "A Revolução Francesa começou em 1789, marcada pela queda da Bastilha.",
		sourceName: "Encyclopaedia Britannica",
		sourceUrl: "https://www.britannica.com/event/French-Revolution",
		difficulty: "MEDIUM",
	},
	{
		categorySlug: "historia",
		prompt: "Em que ano Constantinopla foi tomada pelo Império Otomano?",
		answerValue: "1453",
		answerText: "1453",
		answerUnit: "ano",
		explanation: "A queda de Constantinopla em 1453 encerrou o Império Bizantino.",
		sourceName: "Encyclopaedia Britannica",
		sourceUrl: "https://www.britannica.com/event/Fall-of-Constantinople-1453",
		difficulty: "MEDIUM",
	},
	{
		categorySlug: "historia",
		prompt: "Em que ano a Magna Carta foi selada na Inglaterra?",
		answerValue: "1215",
		answerText: "1215",
		answerUnit: "ano",
		explanation: "O rei João selou a Magna Carta em Runnymede, em junho de 1215.",
		sourceName: "The British Library",
		sourceUrl: "https://www.bl.uk/magna-carta/articles/magna-carta-an-introduction",
		difficulty: "HARD",
	},
	{
		categorySlug: "entretenimento",
		prompt:
			"Em que ano foi lançado Branca de Neve e os Sete Anões, o primeiro longa-metragem animado da Disney?",
		answerValue: "1937",
		answerText: "1937",
		answerUnit: "ano",
		explanation: "Branca de Neve e os Sete Anões estreou em 1937.",
		sourceName: "The Walt Disney Family Museum",
		sourceUrl: "https://www.waltdisney.org/blog/snow-white-and-seven-dwarfs",
		difficulty: "MEDIUM",
	},
	{
		categorySlug: "entretenimento",
		prompt: "Em que ano ocorreu a primeira transmissão de rádio no Brasil?",
		answerValue: "1922",
		answerText: "1922",
		answerUnit: "ano",
		explanation: "A transmissão ocorreu durante as comemorações do centenário da Independência.",
		sourceName: "EBC",
		sourceUrl:
			"https://memoria.ebc.com.br/cultura/2012/09/primeira-transmissao-de-radio-no-brasil-completa-90-anos",
		difficulty: "HARD",
	},
	{
		categorySlug: "entretenimento",
		prompt: "Quantos minutos há em um dia inteiro?",
		answerValue: "1440",
		answerText: "1.440 minutos",
		answerUnit: "minutos",
		explanation: "Um dia tem 24 horas, e cada hora contém 60 minutos.",
		sourceName: "NIST",
		sourceUrl:
			"https://www.nist.gov/pml/time-and-frequency-division/popular-links/time-frequency-z",
		difficulty: "EASY",
	},
	{
		categorySlug: "esportes",
		prompt: "Quantos metros tem aproximadamente a distância total de um Ironman?",
		answerValue: "226000",
		answerText: "cerca de 226.000 metros",
		answerUnit: "metros",
		explanation:
			"A prova combina natação, ciclismo e corrida, somando aproximadamente 226 quilômetros.",
		sourceName: "IRONMAN",
		sourceUrl: "https://www.ironman.com/races",
		difficulty: "HARD",
	},
	{
		categorySlug: "esportes",
		prompt: "Quantos segundos duram os quatro períodos regulamentares de uma partida da NBA?",
		answerValue: "2880",
		answerText: "2.880 segundos",
		answerUnit: "segundos",
		explanation: "A NBA joga quatro períodos de 12 minutos, totalizando 48 minutos regulamentares.",
		sourceName: "NBA",
		sourceUrl: "https://official.nba.com/rule-no-5-scoring-and-timing/",
		difficulty: "MEDIUM",
	},
	{
		categorySlug: "esportes",
		prompt: "Em que ano foi disputada a primeira Copa do Mundo de futebol masculino?",
		answerValue: "1930",
		answerText: "1930",
		answerUnit: "ano",
		explanation: "A primeira Copa do Mundo foi realizada no Uruguai, em 1930.",
		sourceName: "FIFA",
		sourceUrl: "https://www.fifa.com/tournaments/mens/worldcup/uruguay1930",
		difficulty: "EASY",
	},
	{
		categorySlug: "natureza",
		prompt: "Qual é a área aproximada da Floresta Amazônica, em quilômetros quadrados?",
		answerValue: "5500000",
		answerText: "cerca de 5.500.000 km²",
		answerUnit: "km²",
		explanation:
			"A Amazônia é a maior floresta tropical do mundo e se estende por vários países sul-americanos.",
		sourceName: "WWF",
		sourceUrl: "https://www.worldwildlife.org/places/amazon",
		difficulty: "HARD",
	},
	{
		categorySlug: "natureza",
		prompt: "Quantos quilômetros quadrados tem aproximadamente a Antártida?",
		answerValue: "14000000",
		answerText: "cerca de 14.000.000 km²",
		answerUnit: "km²",
		explanation:
			"A Antártida é o continente mais ao sul da Terra e é coberta principalmente por gelo.",
		sourceName: "British Antarctic Survey",
		sourceUrl: "https://www.bas.ac.uk/about/antarctica/",
		difficulty: "HARD",
	},
	{
		categorySlug: "natureza",
		prompt: "Qual é a massa aproximada de uma baleia-azul adulta, em quilogramas?",
		answerValue: "200000",
		answerText: "cerca de 200.000 kg",
		answerUnit: "kg",
		explanation:
			"A baleia-azul é o maior animal conhecido, podendo pesar aproximadamente 200 toneladas.",
		sourceName: "NOAA Fisheries",
		sourceUrl: "https://www.fisheries.noaa.gov/species/blue-whale",
		difficulty: "HARD",
	},
	{
		categorySlug: "cotidiano",
		prompt: "Quantos segundos há em um ano comum de 365 dias?",
		answerValue: "31536000",
		answerText: "31.536.000 segundos",
		answerUnit: "segundos",
		explanation: "O cálculo multiplica 365 dias por 24 horas, 60 minutos e 60 segundos.",
		sourceName: "NIST",
		sourceUrl:
			"https://www.nist.gov/pml/time-and-frequency-division/popular-links/time-frequency-z",
		difficulty: "MEDIUM",
	},
	{
		categorySlug: "cotidiano",
		prompt: "Quantos gramas há em uma tonelada métrica?",
		answerValue: "1000000",
		answerText: "1.000.000 de gramas",
		answerUnit: "gramas",
		explanation: "Uma tonelada métrica equivale a mil quilogramas, ou um milhão de gramas.",
		sourceName: "BIPM",
		sourceUrl: "https://www.bipm.org/en/measurement-units/si-prefixes",
		difficulty: "MEDIUM",
	},
	{
		categorySlug: "cotidiano",
		prompt: "Quantos milímetros há em um quilômetro?",
		answerValue: "1000000",
		answerText: "1.000.000 de milímetros",
		answerUnit: "milímetros",
		explanation: "Um quilômetro tem mil metros, e cada metro tem mil milímetros.",
		sourceName: "BIPM",
		sourceUrl: "https://www.bipm.org/en/measurement-units/si-prefixes",
		difficulty: "MEDIUM",
	},
	{
		categorySlug: "cotidiano",
		prompt: "Quantos bytes há em um terabyte decimal?",
		answerValue: "1000000000000",
		answerText: "1.000.000.000.000 bytes",
		answerUnit: "bytes",
		explanation:
			"No sistema decimal de prefixos SI, tera representa 10 elevado à décima segunda potência.",
		sourceName: "BIPM",
		sourceUrl: "https://www.bipm.org/en/measurement-units/si-prefixes",
		difficulty: "HARD",
	},
]

export async function seedDatabase(prisma: PrismaClient) {
	await prisma.game.upsert({
		where: { slug: HIDDEN_FACE_SLUG },
		update: {
			name: "Rosto Oculto",
			description: "Descubra o avatar secreto eliminando possibilidades em uma mesa para dois.",
			status: "ACTIVE",
			minPlayers: 2,
			maxPlayers: 2,
			durationMin: 20,
		},
		create: {
			slug: HIDDEN_FACE_SLUG,
			name: "Rosto Oculto",
			description: "Descubra o avatar secreto eliminando possibilidades em uma mesa para dois.",
			status: "ACTIVE",
			minPlayers: 2,
			maxPlayers: 2,
			durationMin: 20,
		},
	})
	await prisma.game.upsert({
		where: { slug: MAGICAL_RACE_SLUG },
		update: {
			name: process.env.NEXT_PUBLIC_MAGICAL_RACE_NAME?.trim() || "Corrida Arcana",
			description: "Uma corrida fantástica de poderes imprevisíveis para jogar na mesma mesa.",
			status: "ACTIVE",
			minPlayers: 2,
			maxPlayers: 6,
			durationMin: 30,
		},
		create: {
			slug: MAGICAL_RACE_SLUG,
			name: process.env.NEXT_PUBLIC_MAGICAL_RACE_NAME?.trim() || "Corrida Arcana",
			description: "Uma corrida fantástica de poderes imprevisíveis para jogar na mesma mesa.",
			status: "ACTIVE",
			minPlayers: 2,
			maxPlayers: 6,
			durationMin: 30,
		},
	})
	await prisma.game.upsert({
		where: { slug: NEM_A_PATO_SLUG },
		update: {
			name: "Nem a Pato",
			description: "Um jogo presencial de estimativas numéricas para grupos.",
			status: "ACTIVE",
			minPlayers: 2,
			maxPlayers: 12,
			durationMin: 30,
		},
		create: {
			slug: NEM_A_PATO_SLUG,
			name: "Nem a Pato",
			description: "Um jogo presencial de estimativas numéricas para grupos.",
			status: "ACTIVE",
			minPlayers: 2,
			maxPlayers: 12,
			durationMin: 30,
		},
	})

	const categoryIds = new Map<string, string>()
	for (const category of categories) {
		const savedCategory = await prisma.nemAPatoCategory.upsert({
			where: { slug: category.slug },
			update: { name: category.name },
			create: category,
		})
		categoryIds.set(category.slug, savedCategory.id)
	}
	for (const question of questions) {
		const categoryId = categoryIds.get(question.categorySlug)
		if (!categoryId) throw new Error(`Category not found: ${question.categorySlug}`)

		const data = {
			categoryId,
			answerValue: question.answerValue,
			answerText: question.answerText,
			answerUnit: question.answerUnit,
			explanation: question.explanation,
			sourceName: question.sourceName,
			sourceUrl: question.sourceUrl,
			verifiedAt,
			difficulty: question.difficulty,
			locale: "pt-BR",
			isActive: true,
			isReviewed: true,
		}

		await prisma.nemAPatoQuestion.upsert({
			where: { prompt: question.prompt },
			update: data,
			create: { prompt: question.prompt, ...data },
		})
	}

	const firstAdminEmail = process.env.FIRST_ADMIN_EMAIL?.trim().toLowerCase()
	if (firstAdminEmail) {
		await prisma.user.updateMany({ where: { email: firstAdminEmail }, data: { role: "ADMIN" } })
	}
}
